const DEFAULT_URL="http://localhost:11434";
const state={url:localStorage.getItem("localai.url")||DEFAULT_URL,model:localStorage.getItem("localai.model")||"llama3",systemPrompt:localStorage.getItem("localai.system")||"",temperature:Number(localStorage.getItem("localai.temperature")||0.7),messages:[]};
const $=id=>document.getElementById(id),messagesEl=$("messages");
function render(){if(!state.messages.length){messagesEl.innerHTML='<div class="empty"><h2>Talk to your local AI.</h2><p>Nothing leaves your computer. Choose an Ollama model and start chatting.</p></div>';return}messagesEl.innerHTML=state.messages.map(m=>'<div class="message '+m.role+'"><span class="label">'+(m.role==="user"?"You":"AI")+'</span>'+escapeHtml(m.content)+'</div>').join("");messagesEl.scrollTop=messagesEl.scrollHeight}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function loadModels(){try{const r=await fetch(state.url+"/api/tags"),data=await r.json(),models=data.models||[],select=$("model");select.innerHTML="";if(!models.length){select.innerHTML='<option value="">No models installed</option>';return}models.forEach(m=>{const o=document.createElement("option");o.value=m.name;o.textContent=m.name;select.appendChild(o)});if([...select.options].some(o=>o.value===state.model))select.value=state.model;else state.model=select.value}catch{}}
async function checkOllama(){const status=$("status");try{const r=await fetch(state.url+"/api/tags");if(!r.ok)throw new Error();status.textContent="● Ollama connected";status.className="status ok";await loadModels()}catch{status.textContent="● Ollama unavailable — run ollama serve";status.className="status error"}}
function saveSettings(){state.url=$("ollamaUrl").value.trim().replace(/\/$/,"")||DEFAULT_URL;state.model=$("model").value||state.model;state.systemPrompt=$("systemPrompt").value;state.temperature=Number($("temperature").value)||0.7;localStorage.setItem("localai.url",state.url);localStorage.setItem("localai.model",state.model);localStorage.setItem("localai.system",state.systemPrompt);localStorage.setItem("localai.temperature",String(state.temperature));checkOllama()}
async function sendMessage(text){state.messages.push({role:"user",content:text});render();$("sendBtn").disabled=true;const ai={role:"assistant",content:""};state.messages.push(ai);render();try{const history=state.messages.slice(0,-1);const payload={model:state.model||"llama3",messages:[...(state.systemPrompt?[{role:"system",content:state.systemPrompt}]:[]),...history],stream:true,options:{temperature:state.temperature}};const response=await fetch(state.url+"/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!response.ok)throw new Error("Ollama returned HTTP "+response.status);const reader=response.body.getReader(),decoder=new TextDecoder();let buffer="";while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split("\n");buffer=lines.pop();for(const line of lines){if(!line.trim())continue;const chunk=JSON.parse(line);ai.content+=chunk.message?.content||"";render()}}}catch(e){ai.content="Error: "+e.message;render()}finally{$("sendBtn").disabled=false;$("prompt").focus()}}
$("chatForm").addEventListener("submit",e=>{e.preventDefault();const text=$("prompt").value.trim();if(!text||$("sendBtn").disabled)return;$("prompt").value="";sendMessage(text)});
$("prompt").addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();$("chatForm").requestSubmit()}});
$("settingsBtn").onclick=()=>{$("ollamaUrl").value=state.url;$("systemPrompt").value=state.systemPrompt;$("temperature").value=state.temperature;$("settings").showModal()};
$("closeSettings").onclick=()=>$("settings").close();
$("settingsForm").addEventListener("submit",e=>{e.preventDefault();saveSettings();$("settings").close()});
$("refreshModels").onclick=loadModels;$("clearChat").onclick=()=>{state.messages=[];render();$("settings").close()};render();checkOllama();